### PR TITLE
Initial commit, alpha release

### PR DESCRIPTION
**Pull request by iuravic**
This is an initial release for the new repo. Check out its brief [README](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/blob/master/README.md).

Kindly asking for a thorough review of an initial commit. I initially pushed directly to `master`, and created this dummy branch so that I may create a PR based on something. Please review the full content of the `master` -- it's a small plugin -- including:
- project setup: JS and React scaffolding, PHP, config review
- React code
- plugin and PHP code
- do a test run of the steps below

## This plugin

This plugin works on top of the WooCommerce Memberships, and it introduces "premium archived content" to the site.

## Test site setup

- any WP site with WooCommerce Memberships installed
- run `npm install` and `npm run build` or `npm start`
- activate the plugin

### Configure WooCommerce:
- as also described in the Plugin's README.md (part ["Integration with Memberships Plans"](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive#integration-with-memberships-plans)), first set up a simplest Membership Plan to restrict all Posts. In Dashboard go to `WooCommerce` > `Membersips` > `Membership Plans` and select "Add Membership Plan":
  - add a Plan title
  - in Plan's `Restricted Content` tab, select "Add New Rule": Type "Posts", Accessible "Immediately"
  - publish the Plan

### Check that your WooComm config is correct:
- create a new Post
- notice that a new "Newspack Auto archive" Document panel is available, and simply check that the number of days doesn't go below `1`
- fill the post with
  - a title,
  - enter some _lorem ipsum_ content -- and plenty of it, so that you'll clearly see the WooComm restriction message
- now make sure that Newspack Auto Archive is **off**
- not just that, but also make sure that the checkbox _"Check this box if you want to force the content to be public regardless of any restriction rules that may apply now or in the future"_ is turned **off**, which is located at the bottom of the post, in the `Memberships` panel
- publish this post
- and now view it incognito/logged out, and confirm that the post is restricted to guests

You've now set up the Membership to support this plugin. Let's test the plugin itself.

### Second test -- post stays public until due date:
- edit that same post and Update its Published Date to **5** days ago
- now toggle the "Post is public but will become restricted", and notice how the toggle controls the "Force content to be public" checkbox in the Memberships panel at the bottom of the post
- next, set Newspack Auto Archive toggle to **on**
- set **10** days until it becomes archive
- update the post
- view it in incognito, and confirm that it is still public

### Third test -- post automatically becomes restricted content:
- let's now rig it so that it becomes paid content after a number of days:
- your post was last saved with Publish date **5 days ago**, and configured to become public **10 days** after publishing
- now run this SQL to bring bring the number of days when it becomes Restricted Content to **3** -- the interface will not let you set "days until" this low, because that would be a day in history; it would allow **6** as the minimum number -- you may test this afterwards, but now run this SQL:
```
update wp_postmeta set meta_value = '3' where post_id = _____ and meta_key = 'newspack_woocomm_days_to_auto_archive';
```
- finally reopen the post in incognito, and confirm that by accessing it now, it has just become premium content
- before continuing to test/play some more, please read the next paragraph

### **One important note when testing some more**

If you've kept you Post Editor open during the same time when you accessed the Post in incognito in parallel, the whole state of the Post Editor has now become invalid in your browser -- the state of the Post was just changed in the DB by the incognito request, but it didn't automatically reflect in the Post Editor -- the Post Editor still displays the old Post data/meta. 

That's why you _must_ reload the Post Editor _before_ continuing to test on that same Post some more. Otherwise you will experience behavior which will seem like bugs to you, but won't actually be that (hopefully).

My final remark about this -- that's precisely the reason why I decided to enforce a hard minimum on the "days until auto archive" number, so that it can only be set to +1 day from today as a minimum. This should avoid the Post Editor's state invalidation.

If anyone thinks that this could be a problem, and have ideas how to make it sturdier, please let me know.

### CODE REVIEW

**Comment by adekbadek** [comment]
All works well, some remarks:

1. In the document settings panel, "Newspack Auto archive" label is a bit unintuitive IMO, as this feature is about content restriction.
1. Release-related stuff: `newspack-popups` mentions in package.json should be updated
1. Why are the two `newspack_woocomm_auto_archive_*` functions defined in the global scope and in a separate file?
1. In `WooCommPostAutoArchiveSettingsPanel` component:
    1. Unused `toggleWasChanged` state property
    1. There's no need to copy the props to component state, these can stay as props and the component will be updated when they change. 
    1. Use of `var` keyword is discouraged, only `let` & `const` should be used

**Comment by iuravic** [comment]
@claudiulodro ,

> * If you modify the post publish date backwards, the archive toggle gets un-toggled and the post will be public. Not sure what the intended behavior should be, just some interesting behavior I noticed while trying to move a post's publish date backwards to see if it would trigger the archiving. (To test: Publish a post. Set the archive date for 3 days in the future. Save. Move the publish date back 4 days. Save)

Thank so much for this comment, because it helped uncover an actual bug -- it didn't save all the meta properly for blank new posts! Now fixed the bug, and also addressed your remark.

First an explanation of what happened, then a description of my update.

What happened in your case was that you set a date to start auto archiving in the past. Handling this may seem simple, but actually once you get into the depths of the scenarios, it becomes a bit more tricky :) First of all, I wanted to disable the user being able to set this date in the past, because that would probably be a user error. With this plugin we want to allow three possibilities:
1. set Auto Archive ON with a date in the future
2. if it's a date in the past they want to set, then the archive already became Restricted Content, in which case the proper setting is Auto Archive to OFF and uncheck "force post public" and simply let it be Restricted Content
3. make it permanently public by setting Auto Archive OFF and check the "force post public" forever

This one important update was made in 7c0c0d3c which addresses your scenario:
- added on-save hook to frontend, and when a user tries to Save with a date in the past, the Post Editor alerts them and says "Warning, Auto Archive was set to a date which has already passed. This Post was now updated to be Restricted to Members only.", and then immediately updates the frontend elements

image

Other smaller updates in this same commit:
- no longer copying the props to component state
- removed skip auto-archive logic when viewing content in `wp-admin/` -- the plugin's logic is now more straight forward, since the frontend is now up to it (one more missed part covered in this commit 19c3f5e)
- a bit of refactoring:
    - moved setting default values to component constructor
    - added subscribe event to componentDidUpdate
    - cleaned up render a little bit

> * You only need one of these `is_admin()` checks: https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/blob/master/plugin/class-plugin.php#L107-L114.

That what I thought in the beginning, too. But during the saving, the WP Admin made multiple requests, most of them from `is_admin()` URL, but some actually not -- the request appeared to come from the frontend, and the only way to track that it wasn't was by checking the referrer. However, in 7c0c0d3c I removed that whole is admin check anyways 👍 

> * I don't believe `global $post` will always be defined in the `wp` hook, so you should make sure it's defined before using it. In general [`get_post()`](https://developer.wordpress.org/reference/functions/get_post/) is preferred to directly using the global variable.

Ah I see, thanks for sharing that bit of info! I'm not sure though if I we use `get_post()` in the hook if we do not have the Post's ID 🤔 What I did now is added this check 19c3f5e. I tested it and it seems to work fine -- only proceeds with the logic when a request is made which actually provides the `global $post`. Seem OK now? I tested all the scenarios and they work well.

> * I don't think you need any of the cache flushing stuff: https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/blob/master/plugin/class-plugin.php#L121-L142. WordPress/Atomic will automatically handle cache flushing in a smart way without you needing to manually manage the cache. If you do decide to keep the cache flushing, definitely don't flush the post cache on every single request, because it defeats the purpose of caching. :)

You're right! Now removed in 9edec84. The reason I put there it is that Atomic holds a small retention of this cache, around 1 min, and my tests didn't work immediately with it -- but thats really not important, and it lowers down performance. Thanks for catching this!

**Comment by iuravic** [comment]
@adekbadek 

Thanks so much for giving a look at this PR! I actually wanted to request your review about the React part, but I was preparing to do a few improvements first. I made them now, so if you could please take another look at [this file](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/blob/add/initial-release/src/document-settings/index.js), that's the latest version.

> 1. In the document settings panel, "Newspack Auto archive" label is a bit unintuitive IMO, as this feature is about content restriction.

Ah, I can see how that could be the case. I changed this several times, and each time let it rest for a couple of days. I first had longer and more descriptive labels, but in the end decided this seemed like the simplest label. And I can understand that it's not immediately clear of what this feature is, if one isn't aware of this Plugin being installed for that particular purpose. I did however show this to the Transitions Online people, and they liked it, so that's why I finally decided to use it. But if you have some other suggestions, please share.

> 2. Release-related stuff: `newspack-popups` mentions in package.json should be updated

Thanks for catching that! Updated in 4a71645 (and also updated the `.gitignore`). However now that I try and run `npm run release`, I get the following errors in the log. Do you maybe know what the issue with running the `semantic-release` could be? ... 🤔 

```
  1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/Users/ivanuravic/.nvm/versions/node/v10.15.3/bin/node',
  3 1 verbose cli   '/Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-memberships-auto-archive/node_modules/.bin/npm',
  4 1 verbose cli   'run',
  5 1 verbose cli   'semantic-release' ]
  6 2 info using npm@6.14.6
  7 3 info using node@v10.15.3
  8 4 verbose run-script [ 'presemantic-release',
  9 4 verbose run-script   'semantic-release',
 10 4 verbose run-script   'postsemantic-release' ]
 11 5 info lifecycle newspack-woocomm-auto-archive@0.1.0~presemantic-release: newspack-woocomm-auto-archive@0.1.0
 12 6 info lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: newspack-woocomm-auto-archive@0.1.0
 13 7 verbose lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: unsafe-perm in lifecycle true
 14 8 verbose lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: PATH: /Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-m    emberships-auto-archive/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-    memberships-auto-archive/node_modules/.bin:/Users/ivanuravic/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ivanuravic/repositories/VVV_Newsp    ack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-memberships-auto-archive/node_modules/.bin:/Users/ivanuravic/.nvm/versions/node/v10.15.3/bin:/opt/local/bin:/opt/local/sb    in:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
 15 9 verbose lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: CWD: /Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-me    mberships-auto-archive
 16 10 silly lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: Args: [ '-c', 'semantic-release' ]
 17 11 silly lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: Returned: code: 1  signal: null
 18 12 info lifecycle newspack-woocomm-auto-archive@0.1.0~semantic-release: Failed to exec semantic-release script
 19 13 verbose stack Error: newspack-woocomm-auto-archive@0.1.0 semantic-release: `semantic-release`
 20 13 verbose stack Exit status 1
 21 13 verbose stack     at EventEmitter.<anonymous> (/Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-memberships-auto-archive/node_m    odules/npm/node_modules/npm-lifecycle/index.js:332:16)
 22 13 verbose stack     at EventEmitter.emit (events.js:189:13)
 23 13 verbose stack     at ChildProcess.<anonymous> (/Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-memberships-auto-archive/node_m    odules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 24 13 verbose stack     at ChildProcess.emit (events.js:189:13)
 25 13 verbose stack     at maybeClose (internal/child_process.js:970:16)
 26 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 27 14 verbose pkgid newspack-woocomm-auto-archive@0.1.0
 28 15 verbose cwd /Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-memberships-auto-archive
 29 16 verbose Darwin 19.5.0
 30 17 verbose argv "/Users/ivanuravic/.nvm/versions/node/v10.15.3/bin/node" "/Users/ivanuravic/repositories/VVV_Newspack3/www/tol-staging/public_html/wp-content/plugins/newspack-woocomm-members    hips-auto-archive/node_modules/.bin/npm" "run" "semantic-release"
 31 18 verbose node v10.15.3
 32 19 verbose npm  v6.14.6
 33 20 error code ELIFECYCLE
 34 21 error errno 1
 35 22 error newspack-woocomm-auto-archive@0.1.0 semantic-release: `semantic-release`
 36 22 error Exit status 1
 37 23 error Failed at the newspack-woocomm-auto-archive@0.1.0 semantic-release script.
 38 23 error This is probably not a problem with npm. There is likely additional logging output above.
 39 24 verbose exit [ 1, true ]
```

> 3. Why are the two `newspack_woocomm_auto_archive_*` functions defined in the global scope and in a separate file?

I've just been doing it like this so far -- usually if i had some vanilla JS, I'd put it in a separate file, and enqueue it separately. Could you share if there's a better way to do this?

> 4. In `WooCommPostAutoArchiveSettingsPanel` component:
>    
>    1. Unused `toggleWasChanged` state property
>    2. There's no need to copy the props to component state, these can stay as props and the component will be updated when they change.
>    3. Use of `var` keyword is discouraged, only `let` & `const` should be used

Regarding `i.` and `ii.`, thanks, this was updated in 7c0c0d3, together with several other things:

- no longer copying the props to component state
- moved setting default values to component constructor
- added subscribe event to componentDidUpdate -- when the user tries to Save with a date in the past, it alerts the editor and updates the params
- cleaned up render a little bit

Regarding `iii.`,

ouch, yes definitely ;) Thanks for catching that. Updated in d3cfa86.

**Comment by adekbadek** [comment]
>  I changed this label several times, and each time I let it "rest" for a couple of days. I first had longer and more descriptive labels, but in the end decided that this seems like the simplest label. But if you have some other suggestions, please share. 

I'd got for something like "Automatic Content Restriction".

> However now when I try and run npm run release, I get the following errors in the log. Do you maybe know what the issue with the semantic-release could be?

Hm, this `Failed to exec semantic-release script` errors seems to be at the core of it, but I was able to reproduce it. Can you try reinstalling node modules? I've ran `npm run release` and it failed (as expected) because there is no `release` branch on the remote. 

> usually if i had some vanilla JS, I'd put it in a separate file, and enqueue it separately. Could you share is there's a better way to do this?

The distinction between "vanilla" and "ES6" JS should not be needed here – since there's a bundling mechanism (webpack) in use, whole JS codebase can be treated equally, as "modern JS".
In this case, a helper function is needed by the React component. It can be defined in _a file_ and imported by `src/document-settings/index.js` file as an internal dependency. [Here's how it can look like](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/pull/3/commits/9c71b1bbf81862141d0815702737eaa8cdab8acf).

> no longer copying the props to component state

`meta` prop is still duplicated – observe that all all `this.setState` calls which update state's `meta` key are paired with an `onMetaChange` call. 

> added a `subscribe()` event to `componentDidUpdate`

This is not needed – the component is "subscribed" to all props updates anyway. 

I've made some additional tweaks here: https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/pull/3/commits/56655fa37b5a98888454579ed62f8f69c68677f1

**Comment by iuravic** [comment]
> I'd got for something like "Automatic Content Restriction".

Understood. Thanks for the suggestion. I believe we'll review it again soon when we decide how to package/publish these packages.

> Hm, this `Failed to exec semantic-release script` errors seems to be at the core of it, but I was able to reproduce it. Can you try reinstalling node modules? I've ran `npm run release` and it failed (as expected) because there is no `release` branch on the remote.

I'm afraid I wasn't able to fix this for now.

> The distinction between "vanilla" and "ES6" JS should not be needed here – since there's a bundling mechanism (webpack) in use, whole JS codebase can be treated equally, as "modern JS".
> In this case, a helper function is needed by the React component. It can be defined in _a file_ and imported by `src/document-settings/index.js` file as an internal dependency. [Here's how it can look like](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/pull/3/commits/9c71b1bbf81862141d0815702737eaa8cdab8acf).

Got it, it makes perfect sense. Followed your advice here 9239e6f.

> `meta` prop is still duplicated – observe that all all `this.setState` calls which update state's `meta` key are paired with an `onMetaChange` call.

That is very observant! Thanks!, updated this, and not using state for `metaPayload` any longer. Updated as you recommended in e0cc97a.

> > added a `subscribe()` event to `componentDidUpdate`
> 
> This is not needed – the component is "subscribed" to all props updates anyway.

Right, makes sense, I see that now too. Updated in e0cc97a.
 
> I've made some additional tweaks here: [56655fa](https://github.com/Automattic/newspack-woocomm-memberships-auto-archive/commit/56655fa37b5a98888454579ed62f8f69c68677f1)

Thanks so much for sharing all this... I probably could have just merged this branch of yours, but I used your examples as a learning opportunity, and repeated them on my own just as you showed me.

**Pull request closed without merging**
